version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
    - '27017:27017'    
  server-api:
    build:
      context: ./Server
      dockerfile: DockerFile.dev
    ports:
      - '4200:4200'
    restart: on-failure
    container_name: server-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
  client-app:
    build:
      context: ./Client
      dockerfile: DockerFile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '8080:8080'
    restart: on-failure
    container_name: client-app